// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGaangZ7zPCi79BRMe0te3exqo5d7AKg',
    appId: '1:398905749660:android:d4da5931b6c41b2291bd59',
    messagingSenderId: '398905749660',
    projectId: 'flutter-app-distribution-3fb3d',
    databaseURL: 'https://flutter-app-distribution-3fb3d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-3fb3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCrDZB5Skf7CGBMJmZOdR0weAZQ4eEgEY',
    appId: '1:398905749660:ios:851e4f678ca4ed4b91bd59',
    messagingSenderId: '398905749660',
    projectId: 'flutter-app-distribution-3fb3d',
    databaseURL: 'https://flutter-app-distribution-3fb3d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-3fb3d.appspot.com',
    iosBundleId: 'com.example.flutterCompleteProject',
  );

}